name: fuodz
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/libra"ry/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.7+40

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  awesome_notifications: ^0.6.21
  banner_carousel: ^1.2.1
  basic_utils: ^3.3.3
  cached_network_image: ^3.0.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.4.3
  contained_tab_bar_view: ^0.8.0
  cool_alert: ^1.0.3
  country_picker: ^2.0.6
  cupertino_icons: ^1.0.0
  currency_formatter: ^1.2.0
  custom_clippers: ^2.0.0
  draw_page: ^0.0.2
  dartx: ^1.1.0
  date_time_picker: ^2.1.0
  dio: ^4.0.4
  dio_http_cache_lts: ^0.4.0
  dotted_border: ^2.0.0
  dotted_line: ^3.1.0
  double_back_to_close: ^2.0.0
  dynamic_height_grid_view: ^0.0.3
  equatable: ^2.0.3
  expand_widget: ^2.1.0
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_dynamic_links: ^4.2.5
  firebase_messaging: ^12.0.1
  flag: ^6.0.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.4.0+1
  flutter_form_builder: ^7.5.0
  flutter_icons: ^1.0.0+1
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  flutter_onboard: ^2.0.0
  flutter_pagewise: ^2.0.1
  flutter_rating_bar: ^4.0.0
  flutter_signin_button: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.0.0
  flutter_typeahead: ^4.0.0
  flutter_widget_from_html_core: ^0.8.5+1
  fluttercontactpicker: ^4.7.0
  fluttertoast: ^8.0.8
  flutter_native_splash: ^2.2.7
  geolocator: ^8.0.1
  glass: ^1.0.1+1
  glass_kit: ^2.0.1
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.0
  google_maps_place_picker_mb: ^2.0.0-mb.13
  google_nav_bar: ^5.0.3
  google_places_flutter: ^2.0.3
  google_sign_in: ^5.0.7
  group_radio_button: ^1.0.1
  http: ^0.13.4
  i18n_extension: ^4.0.0
  image_picker: ^0.8.1+4
  in_app_review: ^2.0.2
  inspection: ^0.0.12
  intl: ^0.17.0
  jiffy: ^5.0.0
  line_icons: ^2.0.1
  localize_and_translate: ^4.1.1
  location: ^4.3.0
  map_launcher: ^2.2.3
  masonry_grid: ^1.0.0
  measure_size: ^3.0.1
  package_info: ^2.0.2
  pin_code_fields: ^7.4.0
  pinch_zoom: ^1.0.0
  pretty_dio_logger: ^1.1.1
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  rx_storage: ^2.0.0
  random_string: ^2.1.0
  rx_shared_preferences: ^3.0.0
  rxdart_ext : ^0.2.2
  share: ^2.0.1
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^4.1.0
  singleton: ^0.0.2
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  spider: ^2.1.0
  stacked: ^2.2.7+1
  sticky_headers: ^0.3.0+2
  supercharged: ^2.0.0
  ticketview: ^1.0.0
  timelines: ^0.1.0
  upgrader: ^4.1.1
  url_launcher: ^6.0.9
  velocity_x: ^3.3.0
  what3words: ^3.0.4
  permission_handler: ^10.0.0
  appwrite: ^8.1.0
  

dependency_overrides:
 
  gallery_previewer: ^0.0.3
  # equatable: ^1.0.0
  # geocoder: ^0.2.1
  flutter_polyline_points: ^1.0.0
  rxdart: ^0.27.2
  yaml: ^3.1.0
  plugin_platform_interface: ^2.1.1
  # provider: ^5.0.0
  # photo_view: ^0.12.0

dev_dependencies:
  flutter_application_id: ^2.0.0-dev
  flutter_launcher_icons: ^0.9.2
  # flutter_native_splash: ^2.2.7
 
  flutter_test:
    sdk: flutter
  translator: ^0.1.7

flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/json/
    - assets/lang/
    - assets/R.gif
    - assets/
